name: ✨ Demande de fonctionnalité
description: Proposer une amélioration ou une nouvelle fonctionnalité
labels: ['enhancement']
body:
  - type: textarea
    id: problem
    attributes:
      label: Problème / besoin
      description: Quel problème cette fonctionnalité résout-elle ?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Solution proposée
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives envisagées
    validations:
      required: false
